name: wfesc_app
description: WFESC Android Application
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0

flutter:
  uses-material-design: true

  assets:
    - assets/web/
